export {publications} from './publications.mjs';

export const profile = { name: 'Zitao Wang',
  role: 'Assistant Professor · Hydrogeology',
  institution: 'Anhui University of Science and Technology',
  department: 'School of Earth and Environment',
  introduction:
   'I study reactive transport in saline-lake groundwater, using numerical modelling and data-driven methods to investigate groundwater systems and salt-lake resources.',
  photo: 'assets/avatar-placeholder.svg',
  interests: [ 'Reactive transport', 'Groundwater modelling', 'Salt-lake resources' ],
  emails: [ 'zitao.wang@aust.edu.cn', 'zitao.waung@gmail.com' ],
  links:
   { scholar: 'https://scholar.google.com/citations?user=aIXhXM4AAAAJ',
     orcid: 'https://orcid.org/0000-0002-7776-4282',
     github: 'https://github.com/wangzitao21' },
  updated: 'Updated September 2026' };

export const projects = [ { period: '2026–2028',
    number: '42502241',
    status: 'ongoing',
    role: 'pi',
    title: 'Dynamic evolution of saline-lake brine aquifers and mechanisms of preferential flow-path formation',
    funder: 'National Natural Science Foundation of China' },
  { period: '2024–2026',
    number: '2024M760016',
    status: 'completed',
    role: 'pi',
    title:
     'Solid-liquid transformation mechanisms and reactive transport of potash–lithium deposits under artificial solution mining',
    funder: 'China Postdoctoral Science Foundation' },
  { period: '2025–2026',
    number: 'GZC20250302',
    status: 'completed',
    role: 'pi',
    title: 'Postdoctoral Fellowship Program of China Postdoctoral Science Foundation',
    funder: null },
  { period: '2027–2030',
    number: 'U24A20598',
    status: 'ongoing',
    role: 'subprojectLead',
    pinned: true,
    title:
     'Water–salt dynamics and ecosystem response mechanisms in the salt-lake region of the Qaidam Basin under the combined effects of climate change and resource development',
    funder: 'National Natural Science Foundation of China' },
  { period: '2024–2029',
    number: 'XDB1130101',
    status: 'ongoing',
    role: 'participant',
    title: 'Enhanced extraction and efficient separation of hard-to-recover potassium and lithium resources in salt lakes',
    funder: 'Strategic Priority Research Program of the Chinese Academy of Sciences' },
  { period: '2025–2029',
    number: 'U24A20598',
    status: 'ongoing',
    role: 'participant',
    title:
     'Transport of low-grade potassium-bearing brines and mechanisms of solid–liquid transformation under artificial solution mining',
    funder: 'National Natural Science Foundation of China' } ];

export const experience = [ { period: '2024–Present',
    institution: profile.institution,
    role: 'Assistant Professor',
    detail: profile.department },
  { period: '2024–2026',
    institution: profile.institution,
    role: 'Postdoctoral Researcher',
    detail: profile.department },
  { period: '2021–2024',
    institution: 'University of Chinese Academy of Sciences',
    role: 'PhD in Geology',
    detail: 'Advisor: Prof. Jianping Wang' } ];

export const labels = { projects: 'Research projects',
  navProjects: 'Projects',
  publications: 'Publications',
  navPublications: 'Publications',
  experience: 'Education & experience',
  navExperience: 'Experience',
  contact: 'Contact',
  interests: 'Research interests',
  allPublications: 'Google Scholar',
  email: 'Email',
  pi: 'Principal Investigator',
  subprojectLead: 'Subproject Lead',
  participant: 'Project Participant',
  ongoing: 'Ongoing',
  completed: 'Completed',
  more: 'Show more',
  less: 'Show less',
  count: '{shown} of {total} shown',
  photoPlaceholder: 'Portrait placeholder',
  portrait: 'Portrait of Zitao Wang',
  correspondence: 'Research enquiries and academic correspondence are welcome.',
  workEmail: 'University',
  otherEmail: 'Personal',
  copy: 'Copy',
  copyEmail: 'Copy email address',
  copied: 'Email copied',
  copyFailed: 'Copy unavailable. Please select the email address to copy it.',
  light: 'Light',
  dark: 'Dark',
  switchLight: 'Switch to light mode',
  switchDark: 'Switch to dark mode',
  skip: 'Skip to content',
  pageNav: 'Page sections',
  top: 'Back to top' };
